### ISSUE TITLE
Pages not being rendered

### ISSUE THREAD

**Issue by tina-li-xx** [shamilchoudhury/laravel-user-email-verification#1]
Your pages are not being rendered on the browser, i cloned your repo and tried hitting 127.0.0.1:8000, and it did not render on the browser

**Comment by 0xShamil** [comment]
Did you setup the environment?

**Comment by tina-li-xx** [comment]
yes, i did. 'composer install'.

**Comment by 0xShamil** [comment]
Okay. Good. Now you have to create a `.env` file on the project root and copy the contents from `.env.example` file. Then update the details like database name, password, app key etc. 

I'll update the `README` with complete details within the hour. Check it out for further instructions.

**Comment by tina-li-xx** [comment]
okay. thank you

**Comment by 0xShamil** [comment]
I updated the `README`.  Please follow the steps described and see if it solves your issue.

**Comment by OluwabukolaTina** [comment]
![this](https://user-images.githubusercontent.com/26462912/33220951-76c62244-d14c-11e7-9b83-c87041e5c163.PNG)

is there a reason why i am getting this error?

**Comment by OluwabukolaTina** [comment]
i figured it out already. i forgot to change the database.php in the config folder. Thanks for the help

**Comment by tina-li-xx** [comment]
i changed the database in the config folder already. Thanks for the help

**Comment by tina-li-xx** [comment]
should the $table with the foreign key be created in my phpmyadmin. Mine is not created.  Schema::create('verification_tokens', function (Blueprint $table) {
            $table->increments('id');
           $table->integer('user_id')->unsigned()->index();
            $table->string('token');
           $table->timestamps();
           $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
        });

**Comment by 0xShamil** [comment]
Run `php artisan migrate` after you setup the database connection in `.env` file.

**Comment by tina-li-xx** [comment]
do you have any turorial on changing passwords?
