### ISSUE TITLE
Possible typo in LoginController

### ISSUE THREAD

**Issue by raajnadar** [shamilchoudhury/laravel-user-email-verification#3]
Correct me if I am wrong.

App/Http/Controllers/Auth/LoginController.php go to line number 56. The error returning method should be "withErrors" and not "withError".

After changing to withErrors I am getting the flash message. But I am getting the error as raw HTML.

`Please activate your account. <a href="http://localhost:8000/verify/resend?email=test@gmail.com">Resend?</a>`

The anchor tag is not getting interpreted as HTML tag.

**Note: If this is a genuine issue update your blog post as well.**

**Comment by regensv** [comment]
No, this is not a typo.

Method "withError" in LoginController sets flash message with key "error" through the magic method `Illuminate\Http\RedirectResponse::__call()` that calls `Illuminate\Http\RedirectResponse::with()`.

This flash message rendered in [_notifications.blade.php](https://github.com/shamilchoudhury/laravel-user-email-verification/blob/master/resources/views/layouts/partials/_notifications.blade.php)

The same logic with method "withInfo" in [VerificationController::resend()](https://github.com/shamilchoudhury/laravel-user-email-verification/blob/8af47971dff23308d8094f7896758f36e4b94139/app/Http/Controllers/Auth/VerificationController.php#L34)
